version: "3.8"

services:
  mongo:
    image: mongo
    container_name: team-polls-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: team-polls-backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/team_polls
    volumes:
      - .:/app
    command: node server.js

volumes:
  mongo-data:
